// users
export const LOGIN_FORM = 'LOGIN_FORM';
export const REGISTER_FORM = 'REGISTER_FOR';

export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';